[package]
name = "simple-api-gateway-rs"
version = "0.1.0"
edition = "2021"
description = "A Simple, fast, effiecient api gateway"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.8", features = ["derive"] }
